### ISSUE TITLE
Avoid having a big big file

### ISSUE THREAD

**Issue by ZaniaDeveloper** [shuLhan/go-bindata#13]
It's a very good tool but it generate a really big file (for example, when we have 100 files to include).
It'd generate in several files by adding any option in command line.

**Comment by shuLhan** [comment]
So, you want an option in command line to split generated output into several files?

**Comment by ZaniaDeveloper** [comment]
Exactly.

**Comment by shuLhan** [comment]
@ZaniaDeveloper ,

Since generated output is not suppose to be edited, why would you care for the size of output file?

Do you have use case where this will be helpful for other?

Since we have `-include` option, maybe you can split them by running `go-bindata` several times by using different input. How about that?

**Comment by ZaniaDeveloper** [comment]
The generated files contains APIs like the function `AssetNames()`. With the big sized file, JetBrains (or another editor) just don't want parse 60000 lines and a 3Mo sized file. It's understandable cause a source has not to have a such size.

Therefore, its functions used in other files is not recognized and the editor say that it can't find these functions.

The -include can be a solution but i think i'm not the only one with this case, cause in real case, we'd like include plenty of embedded files. It's a repetitive work to generate several commands to split the file, that becomes an heavy cost if we have to maintain that in several projects.

So, i'll post a PR to fix it up.

**Comment by ZaniaDeveloper** [comment]
Thank you for the merge.
