### ISSUE TITLE
 go-bindata data/ not working properly

### ISSUE THREAD

**Issue by ebonetti** [shuLhan/go-bindata#28]
Hi Shulhan :)
the command `go-bindata data/` generates an ampty asset - [bindata.zip](https://github.com/shuLhan/go-bindata/files/1828692/bindata.zip) - on the other hand `go-bindata data/...` works as expected.

Enrico Bonetti Vieno

P.S.: recently I bumped from github.com/jteeuwen/go-bindata to here, thanks you for keeping it up! :+1:

**Comment by shuLhan** [comment]
I will look into it later, thanks for reporting.
