### ISSUE TITLE
feature request: Flag for arbitrary comment lines

### ISSUE THREAD

**Issue by jeffb4** [shuLhan/go-bindata#30]
When running go-bindata on a .json file, the resulting variable is named like fooJson, which throws an error if a linter is run across it (should be fooJSON).

To avoid the problem, it'd be nice to have the ability to via command line flags insert arbitrary comments into the resulting `.go` file to allow certain rules to be turned off (or links to documentation or whatever people might like).

**Comment by tsal** [comment]
Would it maybe make more sense to implement using the golang/lint example of `commonInitialisms` and maybe filter for those as extensions when creating names that use them?

ref:
https://github.com/golang/lint/blob/master/lint.go#L771

**Comment by shuLhan** [comment]
AFAIK, linter should ignore any file that contains header comment with prefix "Code generated by".  For example, see this issue [1].  I think you should report the issue to the linter that you use.

[1] https://github.com/golang/lint/issues/239
