### ISSUE TITLE
Generated `bindata.go` file depends on unspecified information

### ISSUE THREAD

**Issue by qzmfranklin** [shuLhan/go-bindata#33]
# The Problem

I used the following command to generate the `bindata.go` file:
```bash
go-bindata examples/ca/CA.key
```

The `$PWD` (current working directory) is `/home/zhongming/git/LogiOcean`.

The generated `bindata.go` file contains functions such as the following:
```go

var _bindataHomeZhongmingGitLogiOceanExamplesCaCAkey = []byte(
        "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x97\x37\x0e\xac\x0a\x16\x05\x73\x56\xf1\x73\x34\x02\x1a\xdb\xc1\x0f" +
        "\xf0\xde\x7b\x32\xbc\xf7\x8d\x5d\xfd\xe8\x3d\x4d\x38\x37\xbd\x59\xa9\x82\x53\xff\xf9\x73\x0c\x2f\xca\xc6\x3f\x8e" +
        "\x4b\xff\x63\x39\x72\x40\x7b\xfc\x3f\x2a\x1f\xff\xfd\x00\xba\x2c\x2b\xca\x25\x33\x34\xad\xb2\x74\xcd\xd3\xb0\x57" +
        "\x73\xed\xd9\xb2\x75\xbe\xda\xf9\x48\x72\x1a\x57\x98\xa7\x97\xab\x77\x31\xd9\xbb\xeb\x47\x20\x42\x3e\xf6\xe3\x83" +
        "\xae\x41\x5c\xbf\x8e\x96\x81\xde\x12\x74\xd1\x20\xa8\x4b\x96\xb0\x5a\x05\xc1\x53\x1f\x9c\xfb\x91\xac\x42\xd8\x64" +

(omitted for brevity ...)
```

Apparently, the function name was derived from the *absolute path* of the asset file, which is `/home/zhongming/git/LogiOcean/examples/ca/CA.key`.

This means that if I `git clone` my repo to a different location, `cd` there, and run the same command `go-bindata examples/ca/CA.key`, the generated `bindata.go` file would not be identical.  However, I DO expect them to yield identical generated files in both cases.

The root problem of such function names is that they depend on things that are NOT part of the original command line input.

# Proposed Fix

I'd like to propose modifying the `Scan` function defined in the `fsscanner.go` file to respect relative paths such as in `go-bindata examples/ca/CA.key`. So that the `Translate` function defined in `translate.go` would have relative paths in the assets' `Func` field.

**Comment by shuLhan** [comment]
I think this has been fixed on master.  Can you tried it?

**Comment by qzmfranklin** [comment]
Thanks @shuLhan for the update.

I have just tested. This problem is fixed on commit `39bbb8f7e6f7ffe0a226b35c53cf631880a47540` (master as of this writing).

Thanks!

**Comment by qzmfranklin** [comment]
I do not have anything else to complain about now.  Thanks for the help. Appreciate it. Please feel free to close this issue.

**Comment by shuLhan** [comment]
I am glad it had been resolved. Sorry for long respond.

**Comment by qzmfranklin** [comment]
Out of the very many go-bindata forks, this is the most well-maintained.
Thanks for your time fixing issues! Really appreciate it!
