### ISSUE TITLE
22b7a31 break build when directory and file in it are passed

### ISSUE THREAD

**Issue by graywolf-at-work** [shuLhan/go-bindata#36]
In previous version our workflow of invoking go-bindata on output of `find /path` worked fine, however 3.5.0 has a regression causing invalid output file being generated.

Given dir structure

```
$ tree foo
foo
└── bar

0 directories, 1 file
```

```
$ go-bindata -verbose $(find foo)
+ foo/bar
+ foo/bar
> bindata.go
```

```
+   $ go build -o f .
# foo
./bindata.go:112:5: _bindataFooBar redeclared in this block
        previous declaration at ./bindata.go:82:5
./bindata.go:114:6: bindataFooBarBytes redeclared in this block
        previous declaration at ./bindata.go:84:36
./bindata.go:123:6: bindataFooBar redeclared in this block
        previous declaration at ./bindata.go:93:31
./bindata.go:207:2: duplicate key "foo/bar" in map literal
        previous key at ./bindata.go:206:2
```

**Comment by shuLhan** [comment]
@graywolf-at-work 

Thanks for the report. I have try to fix this on the master branch. Can you test it again? Thank you.

**Comment by graywolf-at-work** [comment]
Thank you for the quick fix! I *does* work for my specific usecase (passing output of `find .`), but in general it still does not de-duplicate input files, as in:

```
/xx # tree foo
foo
├── bar
└── foo

0 directories, 2 files
/xx # /root/go/bin/go-bindata -verbose foo/foo foo/foo
+ foo/foo
+ foo/foo
> bindata.go
/xx # go build -o q .
# foo
./bindata.go:112:5: _bindataFooFoo redeclared in this block
        previous declaration at ./bindata.go:82:5
./bindata.go:114:6: bindataFooFooBytes redeclared in this block
        previous declaration at ./bindata.go:84:36
./bindata.go:123:6: bindataFooFoo redeclared in this block
        previous declaration at ./bindata.go:93:31
./bindata.go:207:2: duplicate key "foo/foo" in map literal
```

Is there any reason no to just deduplicate the input files? Should I make a new issue about this (since my specific one was resolved)?

**Comment by shulhan-tokenomy** [comment]
@graywolf-at-work 

Glad that it work now.

I think that would be another issue. Can you open new issue? Thank you.

**Comment by shuLhan** [comment]
@graywolf-at-work Glad that it work now. Can you open new issue for de-duplication? Thank you.
