### ISSUE TITLE
go-bindata data/ does not work as expected

### ISSUE THREAD

**Issue by svysali** [shuLhan/go-bindata#38]
When running `go-bindata data/`, no files are included in the generated go source file.
However, the recursive option `go-bindata data/...` works.

Issue #28  reported the same problem and it was fixed in v3.5.0.
However, the non-recursive behavior is broken again in the latest master. I suspect it might be because of changes done due to Issue #36 .

**Comment by shuLhan** [comment]
@svysali sorry about that, let me take a look again.
