### ISSUE TITLE
Test cases in "internal/tests" failed due to mismatch of the modTime

### ISSUE THREAD

**Issue by ahrtr** [shuLhan/go-bindata#42]
Note that when other developers clone the repo, the modification time of each file will be the time when the clone occurs, so the modTime mismatch. 

I just checked that the modTime included in all bindata.exp are not the commit time, so I guess it's the time in your local computer or your development environment.  

Anyway, we need to figure out some way to fix this or workaround this. 

```
$ diff bindata.exp bindata.go 
104c104
< 		modTime: time.Unix(1586263518, 0),
---
> 		modTime: time.Unix(1594778652, 0),
134c134
< 		modTime: time.Unix(1586263518, 0),
---
> 		modTime: time.Unix(1594778652, 0),
```

**Comment by shuLhan** [comment]
@ahrtr Did it cause the test become fail? If you have any suggestion, we would happily merge it.

**Comment by ahrtr** [comment]
> @ahrtr Did it cause the test become fail? If you have any suggestion, we would happily merge it.

Yes, the test failed.  I just submitted a PR to workaround this issue, 
https://github.com/shuLhan/go-bindata/pull/43/files
