### ISSUE TITLE
Installation instructions not supported with Go 1.18

### ISSUE THREAD

**Issue by mpchadwick** [shuLhan/go-bindata#48]
`go get` will no longer install the `go-bindata` binary

https://tip.golang.org/doc/go1.18#go-get

In my build script I'm working around this with `GO111MODULE=off`, however it seems like this should support installation via `go install`.

```
GO111MODULE=off go get -u github.com/shuLhan/go-bindata/...
```

Currently I get this when I try to `go install`

```
go install github.com/shuLhan/go-bindata@latest
package github.com/shuLhan/go-bindata is not a main package
make: *** [build] Error 1
```

I'm probably doing something wrong, but just getting up to speed on these Go 1.18 changes and wanted to let you know

**Comment by shuLhan** [comment]
Hi @mpchadwick ,

Thanks for the report. For Go module we use the /v4 directory.

You can use the following command to install the latest binary,

```
go install github.com/shuLhan/go-bindata/v4/cmd/go-bindata@master
```
